name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-non-windows-wheel:
    strategy:
      matrix:
        include:
        - arch: linux_x86_64
          runs-on: ubuntu-latest
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_BUILD: cp314-*
        CIBW_SKIP: cp314-musllinux*
        CIBW_BUILD_FRONTEND: uv
        CIBW_BEFORE_ALL_LINUX: >
          dnf -y install meson gcc libmpeg2-devel cargo rust &&
          git clone https://github.com/jsaowji/libdvdread.git --branch master --depth 1 &&
          cd libdvdread &&
          meson build -D libdvdcss=disabled -Dprefix=/usr &&
          meson compile -C build &&
          meson install -C build &&
          cd .. &&
          git clone https://github.com/jsaowji/a52dec.git --depth 1 &&
          cd a52dec &&
          autoreconf -fiv &&
          ./configure \
              --prefix=/usr \
              --sysconfdir=/etc \
              --localstatedir=/var \
              --enable-shared \
              --enable-static &&
          make &&
          make install
      with:
        output-dir: dist
        extras: uv

    - name: Fix tag
      run: |
        cd dist
        for whl in *.whl; do
          pipx run wheel tags --remove --python-tag py3 --abi-tag none $whl
        done

    - uses: actions/upload-artifact@v7
      with:
        name: dvdsrc2-${{ matrix.arch }}
        path: dist

  build-windows-wheel:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-ca-certificates
          mingw-w64-ucrt-x86_64-a52dec
          mingw-w64-ucrt-x86_64-libmpeg2-git
          mingw-w64-ucrt-x86_64-rust
          mingw-w64-ucrt-x86_64-jq
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-autotools
          mingw-w64-ucrt-x86_64-meson
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-pkgconf
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-uv
          mingw-w64-ucrt-x86_64-git
          mingw-w64-ucrt-x86_64-cmake
          git

    - name: Install libdvdread
      run: |
        git clone https://github.com/jsaowji/libdvdread.git --branch master --depth 1
        pushd libdvdread/
        meson build -D libdvdcss=disabled -Dprefix=/ucrt64 &&
        meson compile -C build &&
        meson install -C build &&
        popd
        rm -rf libdvdread

    - name: Build
      run: |
        libmpeg2_STATIC=1 dvdread_STATIC=1 liba52_STATIC=1 uv build

    - name: Fix tag
      run: |
        cd dist
        for whl in *.whl; do
          uvx wheel tags --remove --python-tag py3 --abi-tag none $whl
        done

    - uses: actions/upload-artifact@v7
      with:
        name: dvdsrc2-sdist
        path: dist/*.tar.gz

    - uses: actions/upload-artifact@v7
      with:
        name: dvdsrc2-win_amd64
        path: dist/*.whl
