name: windows build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            base-devel
            mingw-w64-ucrt-x86_64-ca-certificates
            mingw-w64-ucrt-x86_64-a52dec
            mingw-w64-ucrt-x86_64-libmpeg2-git
            mingw-w64-ucrt-x86_64-libdvdread
            mingw-w64-ucrt-x86_64-rust
            mingw-w64-ucrt-x86_64-jq
      - name: Build dvdsrc2
        run: |
          cargo build --release
      - name: Export version
        working-directory: ./dvdsrc2
        run: |
          echo "ARTIFACT_VERSION=$(cargo read-manifest | jq -r '.version')" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dvdsrc2-windows-${{ env.ARTIFACT_VERSION }}
          path: |
            target/release/dvdsrc2.dll
